Repository Activiti/activiti-cloud-acceptance-tests, pull requests merged in 2018-11, with the labels that each got.

#58 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.75
  pom.xml
Labels: updatebot

#61 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.77
  pom.xml
Labels: updatebot

#68 update org.activiti.cloud.api:activiti-cloud-api-dependencies to 7.0.29
  pom.xml
Labels: in progress, updatebot

#70 Exclude groovy-all from serenity
  pom.xml
Labels: in progress

#69 fix: add activiti-cloud-acceptance-tests-dependencies-tests module
  .gitignore
  activiti-cloud-acceptance-tests-core/pom.xml
  activiti-cloud-acceptance-tests-dependencies/pom.xml
  activiti-cloud-acceptance-tests-shared/pom.xml
  dependencies-tests/pom.xml
  pom.xml
Labels: enhancement, in progress

#71 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions
  pom.xml
Labels: in progress, updatebot

#67 Add get process definitions endpoint for query
  activiti-cloud-acceptance-tests-core/src/main/java/org/activiti/cloud/acc/core/services/query/admin/ProcessQueryAdminService.java
  activiti-cloud-acceptance-tests-core/src/main/java/org/activiti/cloud/acc/core/steps/query/admin/ProcessQueryAdminSteps.java
Labels: in progress

#72 Fix resume process
  activiti-cloud-acceptance-tests-core/src/main/java/org/activiti/cloud/acc/core/services/runtime/ProcessRuntimeService.java
  activiti-cloud-acceptance-tests-core/src/main/java/org/activiti/cloud/acc/core/steps/runtime/ProcessRuntimeBundleSteps.java
Labels: in progress

#74 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions
  pom.xml
Labels: in progress, updatebot
