Repository Activiti/activiti-cloud-acceptance-tests, pull requests merged in 2019-01, with the labels that each got.

#93 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions
  pom.xml
Labels: updatebot

#73 not building image so don't need dockerfile or charts
  Dockerfile
  charts/activiti-cloud-acceptance-tests/.helmignore
  charts/activiti-cloud-acceptance-tests/Chart.yaml
  charts/activiti-cloud-acceptance-tests/Makefile
  charts/activiti-cloud-acceptance-tests/README.md
  charts/activiti-cloud-acceptance-tests/templates/NOTES.txt
  charts/activiti-cloud-acceptance-tests/templates/_helpers.tpl
  charts/activiti-cloud-acceptance-tests/templates/deployment.yaml
  charts/activiti-cloud-acceptance-tests/templates/service.yaml
  charts/activiti-cloud-acceptance-tests/values.yaml
  charts/preview/Chart.yaml
  charts/preview/Makefile
  charts/preview/requirements.yaml
  charts/preview/values.yaml
  skaffold.yaml
Labels: in progress

#96 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions
  pom.xml
Labels: updatebot

#97 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions
  pom.xml
Labels: updatebot

#98 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions
  pom.xml
Labels: updatebot

#99 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions
  pom.xml
Labels: updatebot

#102 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions
  pom.xml
Labels: updatebot

#103 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions
  pom.xml
Labels: updatebot

#104 Implement Notifications Steps for Acceptance Scenarios
  activiti-cloud-acceptance-tests-core/pom.xml
  activiti-cloud-acceptance-tests-core/src/main/java/org/activiti/cloud/acc/core/config/RuntimeTestsConfigurationProperties.java
  activiti-cloud-acceptance-tests-core/src/main/java/org/activiti/cloud/acc/core/services/notifications/NotificationsService.java
  activiti-cloud-acceptance-tests-core/src/main/java/org/activiti/cloud/acc/core/steps/notifications/NotificationsSteps.java
Labels: enhancement

#105 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions
  pom.xml
Labels: updatebot

#107 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions
  pom.xml
Labels: updatebot
