Repository Activiti/activiti-cloud-acceptance-tests, pull requests merged in 2020-01, with the labels that each got.

#252 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#253 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#254 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#255 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#256 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#257 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#258 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#259 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#260 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#261 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#262 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#263 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#264 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#265 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#266 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#267 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#268 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  .travis.yml
  pom.xml
Labels: updatebot

#273 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#274 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#275 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#276 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#277 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#278 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#279 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#280 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#281 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#282 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#283 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#284 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#285 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#286 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#287 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#288 fix: Extracted external dependencies to root pom dependency management
  activiti-cloud-acceptance-tests-dependencies/pom.xml
  pom.xml
Labels: enhancement

#289 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#290 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#291 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#292 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#293 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#294 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#295 fix(NotificationsSteps): Resolved missing complete signal on cancel subscription
  activiti-cloud-acceptance-tests-core/src/main/java/org/activiti/cloud/acc/core/steps/notifications/NotificationsSteps.java
Labels: bug

#296 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#297 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#299 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot

#300 fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop
  pom.xml
Labels: updatebot
